### ISSUE TITLE
/install says database exists after fresh install

### ISSUE THREAD

**Issue by horvan** [Leantime/docker-leantime#24]
Installed leantime docker via docker-compose and head over to mydomain.com/install 

I get a message says databse exists and coannot finish setup

I purged each conmtainer and image leantime and mysql and did a reinstall but the messatge is the same, anyway.

Are there standard crediterials to login as admin now so that the /install step is abandoned?
### config 
```yml
version: '3.3'

services:
   db:
     image: mysql:5.7
     container_name: mysql_leantime
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
         MYSQL_ROOT_PASSWORD: '321.qwerty'
         MYSQL_DATABASE: 'leantime'
         MYSQL_USER: 'admin'
         MYSQL_PASSWORD: '321.qwerty'
     ports:
       - "3307:3306"
     command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
   web:
     image: leantime/leantime:latest
     container_name: leantime
     environment:
         LEAN_DB_HOST: 'mysql_leantime'
         LEAN_DB_USER: 'admin'
         LEAN_DB_PASSWORD: '321.qwerty'
         LEAN_DB_DATABASE: 'leantime'
         LEAN_APP_URL: 'https://m.drupal-tv.de'
     ports:
       - "9000:9000"
       - "8090:80"
     depends_on:
       - db
volumes:
    db_data: {}

```

Pretty standard but added appurl

Any Ideas what I am doing wrong?
