### ISSUE TITLE
Container behind Nginx Proxy (HTTP)

### ISSUE THREAD

**Issue by LikoV2** [Leantime/docker-leantime#26]
Hello,

I'm testing leantime with a docker-compose, and I have an issue with my proxy.

It's a simple Nginx proxy without https yet, as it's a local domain.

Here is my docker-compose:
```
leantime_db:
    image: linuxserver/mariadb
    volumes:
      - ./leantime:/config
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: '321.qwerty'
        MYSQL_DATABASE: 'leantime'
        MYSQL_USER: 'admin'
        MYSQL_PASSWORD: '321.qwerty'
    ports:
      - "3306:3306"

  leantime_web:
    image: local-leantime
    environment:
      LEAN_DB_HOST: 'leantime_db'
      LEAN_DB_USER: 'admin'
      LEAN_DB_PASSWORD: '321.qwerty'
      LEAN_DB_DATABASE: 'leantime'
    ports:
      - "9000:9000"
      - "8125:80"
      - "8126:443"
    depends_on:
      - leantime_db
```
I changed the database image (mysql doesn't run on ARM7 arch) and built the leantime image myself as it's running on a Raspberry Pi 4.

Here is my Nginx reverse-proxy conf:
```
server {
    listen 80;
    server_name work.home;
    access_log /var/log/nginx/work-http.log;
    location /.well-known {
        alias /var/www/html/work.home/.well-known;
    }
    location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://192.168.1.101:8125;
    }
}
```
It's the same template I use for all other services, and it's working great. However I think it's in conflict with Apache inside Leantime.

When I access http://192.168.1.101:8125/install, the installation page pops up.
When I access http://work.home/install, I'm redirected (301) to https.

I tried the `LEAN_APP_URL` settings but it's not working. Does anyone happen to have the same issue ?
