### ISSUE TITLE
500 error after login

### ISSUE THREAD

**Issue by rbrannath** [Leantime/docker-leantime#30]
With the latest version, I get a 500 error after fresh install and login. With version 2.1.4 it works like a charm.

I filled out the /install-Form and tried to login. I got a blank page, so I checked the "docker-compose up"-log:

```
leantime | 127.0.0.1 -  31/Jan/2021:18:20:23 +0000 "GET /index.php" 200
leantime | 127.0.0.1 -  31/Jan/2021:18:20:23 +0000 "GET /css/style.custom.php" 200
leantime | 127.0.0.1 -  31/Jan/2021:18:20:27 +0000 "GET /index.php" 200
leantime | 127.0.0.1 -  31/Jan/2021:18:20:27 +0000 "GET /css/style.custom.php" 200
leantime | 127.0.0.1 -  31/Jan/2021:18:20:39 +0000 "POST /index.php" 200
leantime | 127.0.0.1 -  31/Jan/2021:18:20:40 +0000 "GET /css/style.custom.php" 200
leantime | 127.0.0.1 -  31/Jan/2021:18:20:46 +0000 "GET /index.php" 200
leantime | 127.0.0.1 -  31/Jan/2021:18:20:46 +0000 "GET /css/style.custom.php" 200
leantime | 127.0.0.1 -  31/Jan/2021:18:20:47 +0000 "POST /index.php" 200
leantime | 127.0.0.1 -  31/Jan/2021:18:20:48 +0000 "GET /css/style.custom.php" 200
leantime | 127.0.0.1 -  31/Jan/2021:18:20:50 +0000 "GET /index.php" 200
leantime | 127.0.0.1 -  31/Jan/2021:18:20:51 +0000 "GET /css/style.custom.php" 200
leantime | 127.0.0.1 -  31/Jan/2021:18:20:56 +0000 "POST /index.php" 302
leantime | 127.0.0.1 -  31/Jan/2021:18:20:56 +0000 "GET /index.php" 500
```

Here is my docker-compose.yml (note that I changed the default docker-compose.yml for my needs, e.g. traefik).
```
version: '3.3'

services:
   db:
     image: mysql:5.7
     container_name: mysql_leantime
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     networks:
       - internal
     environment:
         MYSQL_ROOT_PASSWORD: '321.qwerty'
         MYSQL_DATABASE: 'leantime'
         MYSQL_USER: 'admin'
         MYSQL_PASSWORD: '321.qwerty'
     command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
     labels:
       - "traefik.enable=false"
   web:
     image: leantime/leantime:latest
     container_name: leantime
     environment:
         LEAN_DB_HOST: 'mysql_leantime'
         LEAN_DB_USER: 'admin'
         LEAN_DB_PASSWORD: '321.qwerty'
         LEAN_DB_DATABASE: 'leantime'
         LEAN_APP_URL: 'https://{mydomain}'
     networks:
       - traefik_web
       - internal
     labels:
       - "traefik.enable=true"
       - "traefik.docker.network=traefik_web"
       - "traefik.http.routers.leantime.rule=Host(`{mydomain}`)"
       - "traefik.http.routers.leantime.entrypoints=web"
       - "traefik.http.routers.leantime-secure.entrypoints=websecure"
       - "traefik.http.routers.leantime-secure.rule=Host(`{mydomain}`)"
       - "traefik.http.routers.leantime-secure.tls=true"
       - "traefik.http.routers.leantime-secure.tls.certresolver=myresolver"
     depends_on:
       - db
volumes:
   db_data: {}
networks:
   traefik_web:
     external: true
   internal:
     external: false
```
